version: '3'  # version of compose format

services:
  backend-py:
    build: ./backend-py  # path is relative to docker-compose.yml location
    volumes:
      - ./backend-py:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container

  website:
    image: php:apache  # pulling image from DockerHub
    volumes:
      - ./website:/var/www/html # mount
    ports:
      - 5000:80  # host:container
    depends_on:
      - backend-py  # website is not going to work
                    # unless backend-py is running

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 5002:3306  # host:container
    depends_on:
      - backend-py  # db is not going to work
                    # unless backend-py is running

volumes:
  db_data: {}
